version: '3'
services:
 db:
  image: postgres
  volumes:
    - ./tmp/db:/var/lib/postgresql/data
 web:
  build: .
  entrypoint: ./docker-start.sh
  volumes:
   - ./:/example-api
  ports:
    - "3000:3000"
  depends_on:
    - db
volumes:
  example-api-sync:
    external: true